canicacao/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = "Administración Canicacao"
admin.site.site_title = "Administración Canicacao"

#url monitoreo
urlpatterns = patterns('monitoreo.views',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^$', 'IndexView', name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}),
    url(r'^consulta', 'consulta', name='consulta'),
    url(r'^dashboard', 'dashboard', name='dashboard'),

    #indicadores
    url(r'^educacion', 'educacion', name='educacion'),
    url(r'^propiedad', 'propiedad', name='propiedad'),
    url(r'^uso-tierra', 'uso_tierra', name='uso-tierra'),
    url(r'^produccion', 'produccion', name='produccion'),
    url(r'^riesgos', 'riesgos', name='riesgos'),
    url(r'^comercializacion', 'comercializacion', name='comercializacion'),
    url(r'^genero', 'genero', name='genero'),
    url(r'^reforestacion', 'reforestacion', name='reforestacion'),
    url(r'^caracterizacion', 'caracterizacion_terreno', name='caracterizacion-terreno'),
    url(r'^organizacion-productiva', 'organizacion_productiva', name='organizacion-productiva'),
    url(r'^capacitaciones', 'capacitaciones', name='capacitaciones'),
    url(r'^capacitaciones-socio', 'capacitaciones_socio', name='capacitaciones-socio'),
    url(r'^mitigacion', 'mitigacion_riesgos', name='mitigacion-riesgos'),
    url(r'^certificacion', 'tipo_certificacion', name='tipo-certificacion'),
    url(r'^tecnicas', 'tecnicas_aplicadas', name='tipo-tecnicas-aplicadas'),
    url(r'^ampliar-areas-cacao', 'ampliar_areas_cacao', name='ampliar-areas-cacao'),

    #mapa
    url(r'^mapa/$', 'obtener_lista', name='obtener-lista'),

    #filtros
    url(r'^ajax/organi/$', 'get_organi', name='get-organi'),
    url(r'^ajax/munis/$', 'get_munis', name='get-munis'),
    url(r'^ajax/comunies/$', 'get_comunies', name='get-comunies'),
)

urlpatterns += patterns('',
    url(r'^xls/$', 'monitoreo.utils.save_as_xls'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    )

#url organizacion
urlpatterns += patterns('organizacion.views',
    url(r'^org-mapa/$', 'obtener_lista_org', name='obtener-lista-org'),
    url(r'^org/ajax/munis/$', 'get_munis_org', name='get-munis-org'),
    url(r'^organizacion/', 'get_organizacion', name='organizacion'),
    url(r'^org-dashboard/', 'orgdashboard', name='orgdashboard'),
    url(r'^status/', 'status', name='status'),
    url(r'^documentacion/', 'documentacion', name='documentacion'),
    url(r'^datos-productivos/', 'datos_productivos', name='datos-productivos'),
    url(r'^infraestructura/', 'infraestructura', name='infraestructura'),
    url(r'^comercio-organizaciones/', 'comercializacion_organizaciones', name='comercio-organizaciones'),
    url(r'^financiamiento/', 'financiamiento', name='financiamiento'),
    url(r'^lista-organizaciones/', 'lista_organizaciones', name='lista-organizaciones'),
    url(r'^detalle-org/(?P<id>[0-9]+)/$', 'get_org_detail', name='detail-org'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lugar/models.py
# -*- coding: UTF-8 -*-

from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=200)
    codigo = models.CharField(max_length=2, 
                help_text='Código de 2 letras del país, ejemplo : Nicaragua (ni)')

    class Meta:
        verbose_name_plural = "Países"

    def __unicode__(self):
        return self.nombre

class Departamento(models.Model):
    id = models.IntegerField("Código", primary_key=True)
    pais = models.ForeignKey(Pais)
    nombre = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, null=True, help_text="Usado como url unica(autorellenado)")
    extension = models.DecimalField("Extension Territorials", max_digits=10, decimal_places=2, 
                                    null=True, blank=True)
    #latitud = models.FloatField('Latitud', blank=True, null=True)
    #longitud = models.FloatField('Longitud', blank=True, null=True)
    latitud_1 = models.FloatField('Latitud', blank=True, null=True)
    longitud_1 = models.FloatField('Longitud', blank=True, null=True)


    def __unicode__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Departamentos"
        ordering = ['nombre'] 

class Municipio(models.Model):
    id = models.IntegerField("Código", primary_key=True)
    departamento = models.ForeignKey(Departamento)
    nombre = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True, null=True, help_text="Usado como url unica(autorellenado)")
    extension = models.DecimalField("Extension Territorial", max_digits=10, decimal_places=2, blank=True, null=True)
    latitud = models.DecimalField('Latitud', max_digits=8, decimal_places=5, blank=True, null=True)
    longitud = models.DecimalField('Longitud', max_digits=8, decimal_places=5, blank=True, null=True)    

    def __unicode__(self):
        return '%s - %s' % (self.departamento.nombre, self.nombre)
        
    class Meta:
        verbose_name_plural = "Municipios"
        ordering = ['departamento__nombre', 'nombre']

class Comunidad(models.Model):
    municipio = models.ForeignKey(Municipio)
    nombre = models.CharField(max_length=40)

    class Meta:
        verbose_name_plural="Comunidades"
        ordering = ['nombre'] 

    def __unicode__(self):
        return u'%s' % self.nombre

monitoreo/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from lugar.models import *
from organizacion.models import *
from smart_selects.db_fields import ChainedForeignKey
from multiselectfield import MultiSelectField
from django.core.validators import MaxValueValidator,MinValueValidator

# Create your models here.
class Profesion(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Profesión"
		verbose_name_plural = "Profesiones"

class Recolector(models.Model):
	nombre = models.CharField(max_length=200)
	organizacion = models.ForeignKey(Organizacion)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Recolector"
		verbose_name_plural = "Recolectores"

class Tipos_Servicio(models.Model):
	servicio = models.CharField(max_length=200)

	def __unicode__(self):
		return self.servicio

	class Meta:
		verbose_name = "Tipo de Servicio"
		verbose_name_plural = "Tipos de Servicios"

class Beneficios(models.Model):
	beneficio = models.CharField(max_length=200)

	def __unicode__(self):
		return self.beneficio

	class Meta:
		verbose_name = "Beneficio"
		verbose_name_plural = "Beneficios"

class Situacion(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Situación"
		verbose_name_plural = "Situaciones"

class Lista_Certificaciones(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Certificación"
		verbose_name_plural = "Certificaciones"

class Actividades_Produccion(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Actividad de Producción"
		verbose_name_plural = "Actividades de Producción"

class Quien_Certifica(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Quién certifica"
		verbose_name_plural = "Quienes certifican"

class Paga_Certifica(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Quién paga la certifica"
		verbose_name_plural = "Quienes pagan la certificación"

class Destino_Ingresos(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Destino de ingresos percibidos"
		verbose_name_plural = "Destino de ingresos percibidos"

class Tecnologias(models.Model):
	nombre = models.CharField(max_length=200)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Tecnología de secado y almac. cacao"
		verbose_name_plural = "Tecnologías de secado y almac. cacao"

SEXO_CHOICE = (
	(1,'Hombre'),
	(2,'Mujer')
	)

class Persona(models.Model):
	nombre =  models.CharField(max_length=200,verbose_name='Nombre de jefa/e de familia')
	cedula = models.CharField(max_length=20,verbose_name='Cédula de entrevistado/a',null=True,blank=True)
	fecha_nacimiento = models.DateField(verbose_name='Fecha de nacimiento')
	sexo = models.IntegerField(choices=SEXO_CHOICE)
	profesion = models.ForeignKey(Profesion)
	organizacion = models.ForeignKey(Organizacion,verbose_name='A que Organización pertenece')
	#nombre_finca = models.CharField(max_length=200,verbose_name='Nombre de la Finca')
	departamento = models.ForeignKey(Departamento)
	municipio = ChainedForeignKey(
                                Municipio,
                                chained_field="departamento",
                                chained_model_field="departamento",
                                show_all=False, auto_choose=True)
	comunidad = ChainedForeignKey(
                                Comunidad,
                                chained_field="municipio",
                                chained_model_field="municipio",
                                show_all=False, auto_choose=True)
	latitud = models.FloatField(null=True,blank=True)
	longitud = models.FloatField(null=True,blank=True)

	def __unicode__(self):
		return self.nombre

	class Meta:
		verbose_name = "Persona encuestada"
		verbose_name_plural = "Personas encuestadas"
		unique_together = ("cedula",)


class Encuesta(models.Model):
	fecha = models.DateField(verbose_name='Fecha de la encuesta')
	organizacion = models.ForeignKey(Organizacion,verbose_name='Organización que levanta datos')
	recolector = ChainedForeignKey(
                                Recolector,
                                chained_field="organizacion",
                                chained_model_field="organizacion",
                                show_all=False, auto_choose=True)
                                #models.ForeignKey(Recolector,verbose_name='Nombre del encuestador')
	persona =  ChainedForeignKey(
                                Persona,
                                chained_field="organizacion",
                                chained_model_field="organizacion",
                                show_all=False, auto_choose=True)
                                #models.ForeignKey(Persona,verbose_name='Nombre de la persona encuestada')
	anno = models.IntegerField()
	usuario = models.ForeignKey(User)


	def __unicode__(self):
		return self.persona.nombre

	def save(self, *args, **kwargs):
		self.anno = self.fecha.year
		super(Encuesta, self).save(*args, **kwargs)


class Familia(models.Model):
	miembros = models.IntegerField(verbose_name='Número de miembros')
	encuesta = models.ForeignKey(Encuesta)

	class Meta:
		verbose_name = "1-1 Miembros de la Familia"
		verbose_name_plural = "1-1 Miembros de la Familia"

RANGOS_CHOICE = (
		(1,'Hombres mayores 31 años'),
		(2,'Mujeres mayores 31 años'),
		(3,'Hombre joven 19 a 30 años'),
		(4,'Mujer joven 19 a 30 años'),
		(5,'Hombre adoles. 13 a 18 años'),
		(6,'Mujer adoles. 13 a 18 años'),
		(7,'Niños 0 a 12 años'),
		(8,'Niñas 0 a 12 años'),
		(9,'Ancianos (> 64 años)'),
		)

class Educacion(models.Model):
	rango = models.IntegerField(choices=RANGOS_CHOICE,verbose_name='Selección')
	numero_total = models.IntegerField()
	no_lee_ni_escribe = models.IntegerField()
	primaria_incompleta = models.IntegerField()
	primaria_completa = models.IntegerField()
	secundaria_incompleta = models.IntegerField()
	bachiller = models.IntegerField()
	universitario_tecnico = models.IntegerField()
	viven_fuera = models.IntegerField(verbose_name='Número de personas que viven fuera de la finca')
	encuesta = models.ForeignKey(Encuesta)

	class Meta:
		verbose_name = "1-2 Nivel de educación de la Familia"
		verbose_name_plural = "1-2 Nivel de educación de la Familia"

PROPIEDAD_CHOICE = (
	(1,'A nombre del Hombre'),
	(2,'A nombre de la Mujer'),
	(3,'A nombre de Hijas/hijos'),
	(4,'A nombre del Hombre y Mujer'),
	(5,'Colectivo'),
	)

SI_NO_CHOICES = (
	(1,'Si'),
	(2,'No')
	)

class Tenencia_Propiedad(models.Model):
	dueno_propiedad = models.IntegerField(choices=SI_NO_CHOICES,verbose_name='Son ustedes dueños de la propiedad')
	si = models.IntegerField(choices=PROPIEDAD_CHOICE,
		verbose_name='En el caso Si, a nombre de quien esta la propiedad',null=True,blank=True)
	no = models.ForeignKey(Situacion,verbose_name='En el caso que diga NO, especifique la situación',
		null=True,blank=True)
	encuesta = models.ForeignKey(Encuesta)

	class Meta:
		verbose_name = "2 Tenencia de Propiedad"
		verbose_name_plural = "2 Tenencia de Propiedad"

class Uso_Tierra(models.Model):
	area_total = models.FloatField(default='0',verbose_name='Área total en manzanas de la propiedad',
									validators = [MinValueValidator(0), MaxValueValidator(12000)])
	bosque = models.FloatField(default='0',verbose_name='Bosques',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	tacotal = models.FloatField(default='0',verbose_name='Tacotal o área de descanso',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	cultivo_anual = models.FloatField(default='0',verbose_name='Cultivo anual ( que produce en el año)',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	plantacion_forestal = models.FloatField(default='0',verbose_name='Plantación forestal ( madera y leña)',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	area_pasto_abierto = models.FloatField(default='0',verbose_name='Área de pastos abierto',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	area_pasto_arboles = models.FloatField(default='0',verbose_name='Área de pastos con árboles',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	cultivo_perenne = models.FloatField(default='0',verbose_name='Cultivo perenne (frutales)',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	cultivo_semi_perenne = models.FloatField(default='0',verbose_name='Cultivo semi-perenne (musácea, piña)',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	cacao = models.FloatField(default='0',verbose_name='Solo destinado para cacao',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	huerto_mixto_cacao = models.FloatField(default='0',verbose_name='Huerto mixto con cacao',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	cafe = models.FloatField(default='0',verbose_name='Café',
									validators = [MinValueValidator(0), MaxValueValidator(1000)])
	otros = models.FloatField(default='0',validators = [MinValueValidator(0), MaxValueValidator(1000)])
	encuesta = models.ForeignKey(Encuesta)

	class Meta:
		verbose_name = "3 Uso de Tierra"
		verbose_name_plural = "3 Uso de Tierra"


class Reforestacion(models.Model):
	enriquecimiento_bosques = models.IntegerField(choices=SI_NO_CHOICES,verbose_name='Enriquecimiento de los bosques')

templates/monitoreo/ampliar_areas_cacao.html
{% extends "base.html" %}
{% load humanize %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function() {
        $('li.item-consulta').addClass('active');
    });
	$(function () {

    $(document).ready(function () {

        // Build the chart
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Productores con interés de ampliar sus áreas de cacao'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '{point.percentage:.1f}%',
                        color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'black',
                        style: {
                            textShadow: '0 0 3px white'
                        }
                    },
                    showInLegend: true
                }

            },
            series: [{
                name: "Porcentaje",
                colorByPoint: true,
                data: [
                {% for key,value in ampliar_areas.items %}
                {
                    name: "{{key}}",
                    y: {{value}}
                },
                {% endfor %}
                ]
            }]
        });
});
});
</script>
{% endblock extra_js %}

{% block tablero %}
    {% include "monitoreo/datostablero.html" %}
{% endblock tablero %}

{% block content %}
<div class="row">
{% include "monitoreo/filtros.html" %}
</div>

{% include "monitoreo/indicadores.html" %}

<div class="container-fluid contenido-indicador">
    <div class="row">
        <ol class="breadcrumb bread-indicador">
            <li><a href="/dashboard/">Tablero Principal</a></li>
            <li class="active">Ampliación áreas de cacao</li>
        </ol>
    </div>

    <div class="row fila1">
        <div class="col-sm-12 col-md-6 col-lg-6 grafico-left">
            <div class="col-md-6" id="container" style="min-width: 310px;  width: 100%; margin: 0 auto;"></div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 grafico-right">
          <div class="">
              <h4>Áreas totales: {{areas_total|floatformat:2|intcomma}} ha</h4>
              <h4>Promedio de áreas por porductor: {{avg_areas|floatformat:2|intcomma}} ha</h4>
          </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/monitoreo/capacitaciones_socio.html
{% extends "base.html" %}

{% block extra_js %}
	<script>
   $(document).ready(function() {
        
        $('li.item-consulta').addClass('active');
    
    })

$(function () {
    // Create the chart
    $('#cap_socio').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Capacitaciones socioeconómicas recibidas'
        },

        xAxis: {
            type: 'category'
        },
        yAxis: {
            title: {
                text: 'Frecuencia'
            }

        },
        legend: {
            enabled: false
        },
        plotOptions: {
            series: {
                borderWidth: 0,
                dataLabels: {
                    enabled: true,
                    format: '{point.y}'
                }
            }
        },

        tooltip: {
            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y}'
        },

        series: [{
            name: "Capacitaciones",
            colorByPoint: true,
            data: [

            {% for key,value in capacitaciones_socio.items %}
                {
                name: "{{key}}",
                y: {{value}},
                drilldown: "{{key}}"
            },
            {% endfor %}
            ]
        }],

    });
});

	</script>
{% endblock extra_js %}

{% block content %}
<style>
    .table{
        width: 70%;
        margin: 0 auto;
        margin-top: 40px
    }
 .btn-export {
  float: none;
  margin-left: 75%;
  margin-top: 30px;
}
</style>

{% include "monitoreo/filtros.html" %}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 tablero-titulo">
          <h4 class="titulo-inicio"><a href="/dashboard/">Regresar al tablero principal</a></h4>  
        </div>
    </div>
</div>

<div class="col-md-12 col-lg-12">
    <div id="cap_socio" style="min-width: 310px; height: 400px; max-width: 900px;margin: 0 auto"></div>
</div>

<a class="btn-export btn btn-default" href="#" onclick="exportarXLS('modalidad'); return false;">Exportar tabla</a>
<div class="col-md-12 col-lg-12">
<div id="modalidad">
        <table class="table">
            <thead>
                <tr>
                    <th>Capacitaciones socioeconómicas recibidas</th>
                    <th>Hijas</th>
                    <th>Hijos</th>
                    <th>Jefe familia varón</th>
                    <th>Jefa familia mujer</th>
                </tr>
            </thead>
            <tbody>
                {% for key,value in dic_socio.items %}
                    <tr>
                        <td>{{key}}</td>
                        {% for x,y in value.items %}
                            <td>{{y}}</td>
                        {% endfor %}
                    </tr>
                {%endfor%}
            </tbody>
        </table>
        </div>
    </div>


	{% include "monitoreo/indicadores.html" %}
{% endblock content %}

templates/monitoreo/consulta.html
{% extends "base.html" %}

{% block extra_js %}
<!--<link href="/static/css/select2.min.css" rel="stylesheet" />
<script src="/static/js/select2.min.js"></script>-->
<link rel="stylesheet" href="/static/css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="/static/js/bootstrap-multiselect.js"></script>
<script>

$(document).ready(function() {
    $('li.item-consulta').addClass('active');
});
$(document).ready(function() {
    $('#id_anno').multiselect({
        buttonWidth: '250px',
        includeSelectAllOption: true,
        selectAllText: 'Seleccionar todos',
        buttonText: function(options, select) {
                if (options.length === 0) {
                    return 'Sin selección ...';
                }
                else if (options.length > 3) {
                    return 'Varias opciones seleccionadas!';
                }
                 else {
                     var labels = [];
                     options.each(function() {
                         if ($(this).attr('label') !== undefined) {
                             labels.push($(this).attr('label'));
                         }
                         else {
                             labels.push($(this).html());
                         }
                     });
                     return labels.join(', ') + '';
                 }
            }
    });

    $('#id_socio').multiselect({
        buttonWidth: '250px',
    });
    $('#id_organizacion').multiselect({
        buttonWidth: '250px',
        maxHeight: 250,
        includeSelectAllOption: true,
        selectAllText: 'Seleccionar todos',
        buttonText: function(options, select) {
                if (options.length === 0) {
                    return 'Sin selección ...';
                }
                else if (options.length > 3) {
                    return 'Varias opciones seleccionadas!';
                }
                 else {
                     var labels = [];
                     options.each(function() {
                         if ($(this).attr('label') !== undefined) {
                             labels.push($(this).attr('label'));
                         }
                         else {
                             labels.push($(this).html());
                         }
                     });
                     return labels.join(', ') + '';
                 }
            }
    });
    $('#id_departamento').multiselect({
        buttonWidth: '250px',
        maxHeight: 250,
        includeSelectAllOption: true,
        selectAllText: 'Seleccionar todos',
        buttonText: function(options, select) {
            if (options.length === 0) {
                return 'Sin selección ...';
            }
            else if (options.length > 3) {
                return 'Varias opciones seleccionadas!';
            }
             else {
                 var labels = [];
                 options.each(function() {
                     if ($(this).attr('label') !== undefined) {
                         labels.push($(this).attr('label'));
                     }
                     else {
                         labels.push($(this).html());
                     }
                 });
                 return labels.join(', ') + '';
             }
        }
    });
    $('#id_municipio').multiselect({
        enableCollapsibleOptGroups: true,
        buttonWidth: '250px',
        maxHeight: 250,
        includeSelectAllOption: true,
        selectAllText: 'Seleccionar todos',
        buttonText: function(options, select) {
            if (options.length === 0) {
                return 'Sin selección ...';
            }
            else if (options.length > 3) {
                return 'Varias opciones seleccionadas!';
            }
             else {
                 var labels = [];
                 options.each(function() {
                     if ($(this).attr('label') !== undefined) {
                         labels.push($(this).attr('label'));
                     }
                     else {
                         labels.push($(this).html());
                     }
                 });
                 return labels.join(', ') + '';
             }
        }
    });
    $("#id_municipio").multiselect('disable');
});
  

var foo = [];
$(document).on('change','#id_departamento',function(){
         
    $('#id_departamento :selected').each(function(i, selected){ 
        foo[i] = $(selected).val();      
    });
    $.getJSON('/ajax/munis/?ids='+foo.join(","), function(data){
        $('#id_municipio').html('');
        $('#id_municipio').multiselect('enable');
        var municipio = $('#id_municipio')
        if(data){
            
           $.each(data, function(i, item){
            $.each(item, function(j, item2){
                var group = $('<optgroup></optgroup>').attr('label', j);
                $.each(item2, function(k, item3){
                    group.append($('<option></option>').val(item3.id).html(item3.nombre));
                });
                group.appendTo(municipio);
                $('#id_municipio').multiselect('rebuild');
            });
        });
       }
   });
});

var foo2 = [];
$(document).on('change','#id_municipio',function(){
         
    $('#id_municipio :selected').each(function(i, selected){ 
        foo2[i] = $(selected).val();      
    });
    $.getJSON('/ajax/comunies/?ids='+foo2.join(","), function(data){
        $('#id_comunidad').html('');
        $("#id_comunidad").prop("disabled", false);
        if(data){
            $.each(data, function(i, item){
                $('#id_comunidad').append($('<option></option>').val(item.id).html(item.nombre));
                });
       }
   });

     $.getJSON('/ajax/organi/?ids='+foo2.join(","), function(data){
        $('#id_organizacion').html('');
        //$("#id_organizacion").prop("disabled", false);
        if(data){
            $.each(data, function(i, item){
                $('#id_organizacion').append($('<option></option>').val(item.id).html(item.siglas));
                });
       }
   });
});
</script>

{% endblock extra_js %}

{% block content %}
<style type="text/css">
    footer{

        position: inherit;

    }
@media (min-width: 768px){
    footer{

        position: fixed;
        bottom: 0px;
    }
}
    .select2-container--default .select2-selection--multiple .select2-selection__choice {
        background-color: #CB6830 !important;
    }
    .select2-selection__clear {
        color: #CB6830 !important;
    }
</style>

<div class="formulario-consulta">
               <!-- -->
                <div class="filtros">
                    <div class="row">
                    <form action="." method="POST">{% csrf_token %}
                        <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 select-filtro">
                            <div class="form-group">
                                <label >Fecha</label>
                                <br>
                                
                                     {{form.anno}}
                                                   
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 select-filtro">
                            <div class="form-group">
                                <label >Departamento</label>
                                <br>
                                {{form.departamento}}                    
                            </div>

                            <div class="form-group">
                                <label >Municipio</label>
                                <br>
                                {{form.municipio}}                    
                            </div>

                            <!--<div class="form-group">
                                <label >Comunidad</label>
                                <br>
                                {{form.comunidad}}                    
                            </div>-->
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 select-filtro">
                            <div class="form-group">
                                <label >Organización</label>
                                <br>
                               {{form.organizacion}}                    
                            </div>
                            <div class="form-group">
                                <label >Socios</label>
                                <br>
                                {{form.socio}}
                            </div>
                        </div>
                         
                        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 select-filtro">
                            
                          
                            <input type="submit" value="Consultar" class="btn btn-default btn-filtro" name="consulta"/>


                        </div>
                        </form>
                    </div>
                </div>
            </div>

{% endblock content %}